/** Contenido de los 4 paneles del hero testimonial (copy verbatim del brief). */
export const TESTIMONIAL_SLIDES = [
  {
    id: 'carlos',
    name: 'Carlos',
    bg: '#B6C8D1',
    titleLeft: 'La Guía de',
    titleRight: 'Carlos',
    impact: '... y con Guía Pilar tengo superpoderes.',
    portrait: '/images/testimonial/carlos_portrait.jpg',
    cards: [
      {
        slot: 1,
        float: 'slow',
        position: 'top-left',
        type: 'product',
        image: '/images/testimonial/carlos_shoes.jpg',
        imageAlt: 'Par de zapatos marrones',
        cart: true,
        label: 'Gosatería Horrario',
        meta: ['Horarios 9:00 - 1:00 pm.'],
      },
      {
        slot: 2,
        float: 'medium',
        position: 'top-right',
        type: 'google',
        label: '"Zapatería Carlos Pilar"',
        meta: ['Horario 10:00 - 1:00 a.m.'],
        stars: '4.9',
      },
      {
        slot: 3,
        float: 'fast',
        position: 'bottom-left',
        type: 'info',
        label: 'Info del negocio',
        meta: ['Tradición y calidad en Pilar.'],
        chip: 'Verificado',
      },
      {
        slot: 4,
        float: 'medium',
        position: 'bottom-right',
        type: 'info',
        label: 'Contacto',
        meta: ['Samara Carlos · WhatsApp'],
      },
    ],
  },
  {
    id: 'sofia',
    name: 'Sofía',
    bg: '#FFD1D6',
    titleLeft: 'La Guía de',
    titleRight: 'Sofía',
    impact: '... Guía Pilar me ayudó a potenciar mi negocio.',
    portrait: '/images/testimonial/sofia_portrait.jpg',
    cards: [
      {
        slot: 1,
        float: 'slow',
        position: 'top-left',
        type: 'product',
        image: '/images/testimonial/sofia_ceramics.jpg',
        imageAlt: 'Tazas de cerámica coloridas',
        cart: true,
        label: 'Taller de cerámica',
      },
      {
        slot: 2,
        float: 'medium',
        position: 'top-right',
        type: 'map',
        label: 'Taller Pilar',
      },
      {
        slot: 3,
        float: 'fast',
        position: 'bottom-left',
        type: 'social',
        image: '/images/testimonial/sofia_insta.jpg',
        imageAlt: 'Sofía trabajando en el torno',
      },
      {
        slot: 4,
        float: 'medium',
        position: 'bottom-right',
        type: 'cta',
        cta: 'Ver taller',
        ctaIcon: '✨',
      },
    ],
  },
  {
    id: 'pedro',
    name: 'Pedro',
    bg: '#C7E1C7',
    titleLeft: 'La Guía de',
    titleRight: 'Pedro',
    impact: '... con Guía Pilar estoy más cerca de mis clientes de siempre.',
    portrait: '/images/testimonial/pedro_portrait.jpg',
    cards: [
      {
        slot: 1,
        float: 'slow',
        position: 'top-left',
        type: 'product',
        image: '/images/testimonial/pedro_bike1.jpg',
        imageAlt: 'Bicicleta vintage de perfil',
        label: 'Restauración',
      },
      {
        slot: 2,
        float: 'medium',
        position: 'top-right',
        type: 'cta',
        cta: 'Agendar Cita',
        ctaIcon: '📅',
      },
      {
        slot: 3,
        float: 'fast',
        position: 'bottom-left',
        type: 'gallery',
        images: [
          { src: '/images/testimonial/pedro_bike2.jpg', alt: 'Bicicleta vista frontal' },
          { src: '/images/testimonial/pedro_bike3.jpg', alt: 'Detalle del cuadro de bicicleta' },
        ],
      },
      {
        slot: 4,
        float: 'medium',
        position: 'bottom-right',
        type: 'info',
        label: 'Bicicletero Pilar',
        meta: ['Clásicas y vintage.'],
        chip: 'A domicilio',
      },
    ],
  },
  {
    id: 'elena',
    name: 'Elena',
    bg: '#F9CA57',
    titleLeft: 'La Guía de',
    titleRight: 'Elena',
    impact: '... y Guía Pilar me conectó con los comercios del barrio.',
    portrait: '/images/testimonial/elena_portrait.jpg',
    cards: [
      {
        slot: 1,
        float: 'slow',
        position: 'top-left',
        type: 'product',
        image: '/images/testimonial/elena_mural1.jpg',
        imageAlt: 'Mural urbano',
        label: 'Portfolio',
      },
      {
        slot: 2,
        float: 'medium',
        position: 'top-right',
        type: 'contact',
        label: 'Contacto',
        meta: ['elena@arte.pilar'],
        cta: 'Cotizar Mural',
        ctaLarge: true,
      },
      {
        slot: 3,
        float: 'fast',
        position: 'bottom-left',
        type: 'product',
        image: '/images/testimonial/elena_studio.jpg',
        imageAlt: 'Elena en su estudio de arte',
        label: 'Estudio',
      },
      {
        slot: 4,
        float: 'medium',
        position: 'bottom-right',
        type: 'info',
        label: 'Murales',
        meta: ['Arte urbano en Pilar.'],
        chip: 'Disponible',
      },
    ],
  },
]
